version: '3'

services:
  cqbot:
    build: .
    image: cqbot
    container_name: 'cqbot'
    ports:
      - '1551:1551'
    volumes:
      - db:/app/db
      - logs:/app/logs

volumes:
  db:
  logs:
